//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Transliterator.rc
//
#define IDR_TRANSLITERATOR              100
#define IDD_PROFILEDETAILS              201
#define IDD_TRANSLATEFILES              202
#define IDD_ABOUT                       203
#define IDD_OPTIONS                     204
#define IDD_PAGEGENERAL                 205
#define IDD_PAGEVIEW                    206
#define IDD_PAGEHOTKEYS                 207
#define IDD_PAGEPROFILE                 208
#define IDD_PROFILETRANSLATION          210
#define IDD_PROFILEIGNORE               211
#define IDD_PROFILEEXPORTIMPORT         212
#define IDD_PROFILECOPYPROFILE          213
#define IDD_PROFILENAME                 214
#define IDD_PROFILERESET                215
#define IDR_PROFILE                     220
#define IDR_TRAYICON                    221
#define IDR_EDIT                        222
#define IDC_RELANGTOP                   1000
#define IDC_RELANGBOTTOM                1001
#define IDC_GRPLANGTOP                  1002
#define IDC_GRPLANGBOTTOM               1003
#define IDC_STATICSEPARATOR             1004
#define IDC_LBLPROFILE                  1005
#define IDC_CMBPROFILE                  1006
#define IDC_LBLVIEW                     1007
#define IDC_CMBVIEW                     1008
#define IDC_REDETAILS                   1009
#define IDC_LBLEMAIL                    1010
#define IDC_BTNEMAIL                    1011
#define IDC_LBLSITE                     1012
#define IDC_BTNSITE                     1013
#define IDC_LBLABOUTPROGRAM             1014
#define IDC_EDTABOUT                    1015
#define IDC_GRPPATH                     1016
#define IDC_CMBPATH                     1017
#define IDC_BTNBROWSE                   1018
#define IDC_GRPFOLDER                   1019
#define IDC_CHKSELFOLDER                1020
#define IDC_CHKALLFILES                 1021
#define IDC_CHKALLFOLDERS               1022
#define IDC_CHKALLSUBFOLDERS            1023
#define IDC_GRPFILE                     1024
#define IDC_CHKNAME                     1025
#define IDC_CHKENTRY                    1026
#define IDC_CHKMP3TAGV1                 1027
#define IDC_CHKMP3TAGV2                 1028
#define IDC_GRPPROFILE                  1029
#define IDC_GRPDIRECTION                1030
#define IDC_CMBDIRECTION                1031
#define IDC_GRPIGNORE                   1032
#define IDC_CHKUSEIGNORE                1033
#define IDC_GRPEXTRA                    1034
#define IDC_EDTPREFIX                   1035
#define IDC_EDTSUFFIX                   1036
#define IDC_LBLPREFIX                   1037
#define IDC_LBLSUFFIX                   1038
#define IDC_BTNTRANSLATE                1039
#define IDC_BTNAPPLY                    1040
#define IDC_LSTOPTIONS                  1041
#define IDC_GRPOPTIONPLACE              1042
#define IDC_GRPLANGUAGE                 1043
#define IDC_RADENGLISH                  1044
#define IDC_RADRUSSIAN                  1045
#define IDC_RADBELARUSIAN               1046
#define IDC_RADTRANSLIT                 1047
#define IDC_GRPHOTKEYS                  1048
#define IDC_GRPAUTOTRANSLITERATION      1049
#define IDC_CMBACTION                   1050
#define IDC_HKACTION                    1051
#define IDC_LBLACTION                   1052
#define IDC_LBLHOTKEY                   1053
#define IDC_RADLANGTOPTOLANGBOTTOM      1054
#define IDC_RADLANGBOTTOMTOLANGTOP      1055
#define IDC_GRPCAPTION                  1056
#define IDC_CHKCAPTIONPROFILE           1057
#define IDC_CHKCAPTIONCOUNT             1058
#define IDC_GRPSTATUSBAR                1059
#define IDC_CHKSTATUSBARCOUNT           1060
#define IDC_GRPTRAYICON                 1061
#define IDC_CHKTRAYICONSHOW             1062
#define IDC_GRPTASKBAR                  1063
#define IDC_CHKTASKBARSHOW              1064
#define IDC_GRPPLACEMENT                1065
#define IDC_RADNORMAL                   1066
#define IDC_RADONTOP                    1067
#define IDC_RADONBOTTOM                 1068
#define IDC_GRPCONTROLS                 1069
#define IDC_CHKWRAPTEXT                 1070
#define IDC_CHKSCROLLTEXT               1071
#define IDC_GRPFONTS                    1072
#define IDC_REFONTLANGTOP               1073
#define IDC_REFONTLANGBOTTOM            1074
#define IDC_REFONTDetails               1075
#define IDC_BTNFONTLANGTOP              1076
#define IDC_BTNFONTLANGBOTTOM           1077
#define IDC_BTNFONTPROFILEDETAILS       1078
#define IDC_GRPLOADONSTARTUP            1079
#define IDC_RADLOADNO                   1080
#define IDC_RADLOADSHOWN                1081
#define IDC_RADLOADHIDDEN               1082
#define IDC_CHKSAVETEXTONEXIT           1083
#define IDC_GRPSTORAGE                  1084
#define IDC_GRPSTORAGETEXT              1085
#define IDC_RADTEXTREGISTRY             1086
#define IDC_RADTEXTFILE                 1087
#define IDC_GRPSTORAGEPROFILES          1088
#define IDC_RADPROFILESREGISTRY         1089
#define IDC_RADPROFILESFILE             1090
#define IDC_LBLTOP                      1091
#define IDC_LBLBOTTOM                   1092
#define IDC_EDTLANGTOP                  1093
#define IDC_EDTLANGBOTTOM               1094
#define IDC_LBLPROFILENAME              1095
#define IDC_EDTPROFILENAME              1096
#define IDC_BTNSET                      1097
#define IDC_TABPROFILEACTION            1098
#define IDC_GRPPROFILEACTION            1099
#define IDC_LBLLANGTOP                  1100
#define IDC_LBLLANGBOTTOM               1101
#define IDC_LBLBEGIN                    1102
#define IDC_LBLLANGTOP2                 1102
#define IDC_LBLEND                      1103
#define IDC_REBEGINTOP                  1104
#define IDC_REENDTOP                    1105
#define IDC_REBEGINBOTTOM               1106
#define IDC_REENDBOTTOM                 1107
#define IDC_BTNADD                      1108
#define IDC_BTNDELETE                   1109
#define IDC_LVTRANSLATION               1110
#define IDC_CHKLANGTOPTOLANGBOTTOM      1112
#define IDC_CHKLANGBOTTOMTOLANGTOP      1113
#define IDC_LVIGNORETEXT                1114
#define IDC_GRPIGNORETEXT               1115
#define IDC_RETEXT                      1116
#define IDC_LBLTEXT                     1117
#define IDC_GRPNAME                     1118
#define IDC_GRPCOPYPROFILE              1119
#define IDC_LBLFROM                     1120
#define IDC_LBLTO                       1121
#define IDC_CMBFROM                     1122
#define IDC_CMBTO                       1123
#define IDC_BTNCOPY                     1124
#define IDC_GRPRESET                    1125
#define IDC_CHKRESETTRANSLATION         1126
#define IDC_CHKRESETIGNORE              1127
#define IDC_CHKRESETIGNORETEXT          1128
#define IDC_CHKRESETNAME                1129
#define IDC_BTNRESET                    1130
#define IDC_GRPEXPORTIMPORT             1131
#define IDC_CHKUNICODE                  1132
#define IDC_LBLPATH                     1133
#define IDC_EDTPATH						1134
#define IDC_BTNEXPORT                   1135
#define IDC_BTNIMPORT                   1136
#define ID_PROFILE                      32780
#define ID_EDIT_IGNORE_INSERT           32781
#define ID_EDIT_IGNORE_REMOVE           32782
#define ID_EDIT_COPY_LANGTOPTOLANGBOTTOM 32783
#define ID_EDIT_COPY_LANGBOTTOMTOLANGTOP 32784
#define ID_TOOLS_PROFILEDETAILS         32785
#define ID_TOOLS_TRANSLATEFILES         32786
#define ID_TOOLS_OPTIONS                32787
#define ID_TOOLS_ACTION_TRANSLITERATION 32788
#define ID_TOOLS_ACTION_IGNORE          32789
#define ID_TOOLS_ACTION_IGNORETEXT      32800
#define ID_TOOLS_ACTION_COPYIGNORE      32801
#define ID_PROFILE1                     32811
#define ID_PROFILE2                     32812
#define ID_PROFILE3                     32813
#define ID_PROFILE4                     32814
#define ID_PROFILE5                     32815
#define ID_PROFILE6                     32816
#define ID_PROFILE7                     32817
#define ID_PROFILE8                     32818
#define ID_PROFILE9                     32819
#define ID_PROFILE10                    32820
#define ID_SHOW                         32821
#define ID_HIDE                         32822
#define ID_COUNTLANGTOP                 32823
#define ID_COUNTLANGBOTTOM              32824
#define IDS_ERROR                       62000
#define IDS_HELP                        62001
#define IDS_TRANSLATION                 62002
#define IDS_IGNORE                      62003
#define IDS_IGNORETEXT                  62004
#define IDS_ALL                         62005
#define IDS_DONE                        62006
#define IDS_BOLD                        62007
#define IDS_ITALIC                      62008
#define IDS_UNDERLINE                   62009
#define IDS_STRIKEOUT                   62010
#define IDS_NEWVERSION                  62011
#define IDS_IMPORT						62012
#define IDS_EXPORT						62013
#define IDS_TRANSLATEFILES				62014
#define IDS_BEGIN						62015
#define IDS_END							62016
#define	IDS_TRANSLITERATOR_IS_RUNNING	62017


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_DETAILS
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
