#include "stdafx.hpp"
#include "profiles.hpp"

void profiles::init_profile1(profile& p)
{
    // Profile Name
    p.m_profile_name = L"Standard";

    // Lang Name
    p.m_lang_name[0] = L"Translit";
    p.m_lang_name[1] = L"Cyrillic";

    // Translation
    static const lang_type_nc translation[] =
    {
        lang_type_nc(L"a",    L"à", bimap_direction::all_to_all),
        lang_type_nc(L"A",    L"À", bimap_direction::all_to_all),
        lang_type_nc(L"b",    L"á", bimap_direction::all_to_all),
        lang_type_nc(L"B",    L"Á", bimap_direction::all_to_all),
        lang_type_nc(L"c",    L"ö", bimap_direction::all_to_all),
        lang_type_nc(L"C",    L"Ö", bimap_direction::all_to_all),
        lang_type_nc(L"ch",   L"÷", bimap_direction::all_to_all),
        lang_type_nc(L"cH",   L"÷", bimap_direction::left_to_right),
        lang_type_nc(L"CH",   L"×", bimap_direction::all_to_all),
        lang_type_nc(L"Ch",   L"×", bimap_direction::left_to_right),
        lang_type_nc(L"d",    L"ä", bimap_direction::all_to_all),
        lang_type_nc(L"D",    L"Ä", bimap_direction::all_to_all),
        lang_type_nc(L"e",    L"å", bimap_direction::all_to_all),
        lang_type_nc(L"E",    L"Å", bimap_direction::all_to_all),
        lang_type_nc(L"e'",   L"¸", bimap_direction::all_to_all),
        lang_type_nc(L"E'",   L"¨", bimap_direction::all_to_all),
        lang_type_nc(L"e`",   L"ý", bimap_direction::all_to_all),
        lang_type_nc(L"E`",   L"Ý", bimap_direction::all_to_all),
        lang_type_nc(L"e''",  L"º", bimap_direction::all_to_all),
        lang_type_nc(L"E''",  L"ª", bimap_direction::all_to_all),
        lang_type_nc(L"f",    L"ô", bimap_direction::all_to_all),
        lang_type_nc(L"F",    L"Ô", bimap_direction::all_to_all),
        lang_type_nc(L"g",    L"ã", bimap_direction::all_to_all),
        lang_type_nc(L"G",    L"Ã", bimap_direction::all_to_all),
        lang_type_nc(L"g'`",  L"´", bimap_direction::all_to_all),
        lang_type_nc(L"g`'",  L"´", bimap_direction::left_to_right),
        lang_type_nc(L"G'`",  L"¥", bimap_direction::all_to_all),
        lang_type_nc(L"G`'",  L"¥", bimap_direction::left_to_right),
        lang_type_nc(L"h",    L"õ", bimap_direction::all_to_all),
        lang_type_nc(L"H",    L"Õ", bimap_direction::all_to_all),
        lang_type_nc(L"i",    L"è", bimap_direction::all_to_all),
        lang_type_nc(L"I",    L"È", bimap_direction::all_to_all),
        lang_type_nc(L"i'",   L"³", bimap_direction::all_to_all),
        lang_type_nc(L"I'",   L"²", bimap_direction::all_to_all),
        lang_type_nc(L"i`",   L"¿", bimap_direction::all_to_all),
        lang_type_nc(L"I`",   L"¯", bimap_direction::all_to_all),
        lang_type_nc(L"j",    L"æ", bimap_direction::all_to_all),
        lang_type_nc(L"J",    L"Æ", bimap_direction::all_to_all),
        lang_type_nc(L"k",    L"ê", bimap_direction::all_to_all),
        lang_type_nc(L"K",    L"Ê", bimap_direction::all_to_all),
        lang_type_nc(L"l",    L"ë", bimap_direction::all_to_all),
        lang_type_nc(L"L",    L"Ë", bimap_direction::all_to_all),
        lang_type_nc(L"m",    L"ì", bimap_direction::all_to_all),
        lang_type_nc(L"M",    L"Ì", bimap_direction::all_to_all),
        lang_type_nc(L"n",    L"í", bimap_direction::all_to_all),
        lang_type_nc(L"N",    L"Í", bimap_direction::all_to_all),
        lang_type_nc(L"o",    L"î", bimap_direction::all_to_all),
        lang_type_nc(L"O",    L"Î", bimap_direction::all_to_all),
        lang_type_nc(L"p",    L"ï", bimap_direction::all_to_all),
        lang_type_nc(L"P",    L"Ï", bimap_direction::all_to_all),
        lang_type_nc(L"q",    L"û", bimap_direction::left_to_right),
        lang_type_nc(L"Q",    L"Û", bimap_direction::left_to_right),
        lang_type_nc(L"r",    L"ð", bimap_direction::all_to_all),
        lang_type_nc(L"R",    L"Ð", bimap_direction::all_to_all),
        lang_type_nc(L"s",    L"ñ", bimap_direction::all_to_all),
        lang_type_nc(L"S",    L"Ñ", bimap_direction::all_to_all),
        lang_type_nc(L"sh",   L"ø", bimap_direction::all_to_all),
        lang_type_nc(L"sH",   L"ø", bimap_direction::left_to_right),
        lang_type_nc(L"SH",   L"Ø", bimap_direction::all_to_all),
        lang_type_nc(L"Sh",   L"Ø", bimap_direction::left_to_right),
        lang_type_nc(L"sh''", L"ù", bimap_direction::left_to_right),
        lang_type_nc(L"sH''", L"ù", bimap_direction::left_to_right),
        lang_type_nc(L"Sh''", L"Ù", bimap_direction::left_to_right),
        lang_type_nc(L"SH''", L"Ù", bimap_direction::left_to_right),
        lang_type_nc(L"sch'", L"ù", bimap_direction::all_to_all),
        lang_type_nc(L"sCh'", L"ù", bimap_direction::left_to_right),
        lang_type_nc(L"scH'", L"ù", bimap_direction::left_to_right),
        lang_type_nc(L"sCH'", L"ù", bimap_direction::left_to_right),
        lang_type_nc(L"Sch'", L"Ù", bimap_direction::left_to_right),
        lang_type_nc(L"SCh'", L"Ù", bimap_direction::left_to_right),
        lang_type_nc(L"ScH'", L"Ù", bimap_direction::left_to_right),
        lang_type_nc(L"SCH'", L"Ù", bimap_direction::all_to_all),
        lang_type_nc(L"t",    L"ò", bimap_direction::all_to_all),
        lang_type_nc(L"T",    L"Ò", bimap_direction::all_to_all),
        lang_type_nc(L"tc'",  L"ö", bimap_direction::left_to_right),
        lang_type_nc(L"tC'",  L"ö", bimap_direction::left_to_right),
        lang_type_nc(L"Tc'",  L"Ö", bimap_direction::left_to_right),
        lang_type_nc(L"TC'",  L"Ö", bimap_direction::left_to_right),
        lang_type_nc(L"u",    L"ó", bimap_direction::all_to_all),
        lang_type_nc(L"U",    L"Ó", bimap_direction::all_to_all),
        lang_type_nc(L"u'",   L"¢", bimap_direction::all_to_all),
        lang_type_nc(L"U'",   L"¡", bimap_direction::all_to_all),
        lang_type_nc(L"v",    L"â", bimap_direction::all_to_all),
        lang_type_nc(L"V",    L"Â", bimap_direction::all_to_all),
        lang_type_nc(L"w",    L"ø", bimap_direction::left_to_right),
        lang_type_nc(L"W",    L"Ø", bimap_direction::left_to_right),
        lang_type_nc(L"w''",  L"ù", bimap_direction::left_to_right),
        lang_type_nc(L"W''",  L"Ù", bimap_direction::left_to_right),
        lang_type_nc(L"x",    L"õ", bimap_direction::left_to_right),
        lang_type_nc(L"X",    L"Õ", bimap_direction::left_to_right),
        lang_type_nc(L"y",    L"é", bimap_direction::all_to_all),
        lang_type_nc(L"Y",    L"É", bimap_direction::all_to_all),
        lang_type_nc(L"ya",   L"ÿ", bimap_direction::all_to_all),
        lang_type_nc(L"yA",   L"ÿ", bimap_direction::left_to_right),
        lang_type_nc(L"YA",   L"ß", bimap_direction::all_to_all),
        lang_type_nc(L"Ya",   L"ß", bimap_direction::left_to_right),
        lang_type_nc(L"yu",   L"þ", bimap_direction::all_to_all),
        lang_type_nc(L"yU",   L"þ", bimap_direction::left_to_right),
        lang_type_nc(L"YU",   L"Þ", bimap_direction::all_to_all),
        lang_type_nc(L"Yu",   L"Þ", bimap_direction::left_to_right),
        lang_type_nc(L"y'",   L"û", bimap_direction::all_to_all),
        lang_type_nc(L"Y'",   L"Û", bimap_direction::all_to_all),
        lang_type_nc(L"z",    L"ç", bimap_direction::all_to_all),
        lang_type_nc(L"Z",    L"Ç", bimap_direction::all_to_all),
        lang_type_nc(L"'",    L"ü", bimap_direction::all_to_all),
        lang_type_nc(L"''",   L"Ü", bimap_direction::all_to_all),
        lang_type_nc(L"`",    L"ú", bimap_direction::all_to_all),
        lang_type_nc(L"``",   L"Ú", bimap_direction::all_to_all),
    };
    
    p.m_translation.insert(translation, end(translation));
}