#include "stdafx.hpp"
#include "profiles.hpp"

void profiles::init_profile3(profile& p)
{
    // Profile Name
    p.m_profile_name = L"GOST";

    // Lang Name
    p.m_lang_name[0] = L"Translit";
    p.m_lang_name[1] = L"Cyrillic";

    // Translation
    static const lang_type_nc translation[] =
    {
        lang_type_nc(L"a",    L"à", bimap_direction::all_to_all),
        lang_type_nc(L"A",    L"À", bimap_direction::all_to_all),
        lang_type_nc(L"b",    L"á", bimap_direction::all_to_all),
        lang_type_nc(L"B",    L"Á", bimap_direction::all_to_all),
        lang_type_nc(L"v",    L"â", bimap_direction::all_to_all),
        lang_type_nc(L"V",    L"Â", bimap_direction::all_to_all),
        lang_type_nc(L"w",    L"â", bimap_direction::left_to_right),
        lang_type_nc(L"W",    L"Â", bimap_direction::left_to_right),
        lang_type_nc(L"g",    L"ã", bimap_direction::all_to_all),
        lang_type_nc(L"G",    L"Ã", bimap_direction::all_to_all),
        lang_type_nc(L"d",    L"ä", bimap_direction::all_to_all),
        lang_type_nc(L"D",    L"Ä", bimap_direction::all_to_all),
        lang_type_nc(L"e",    L"å", bimap_direction::all_to_all),
        lang_type_nc(L"E",    L"Å", bimap_direction::all_to_all),
        lang_type_nc(L"jo",   L"¸", bimap_direction::all_to_all),
        lang_type_nc(L"jO",   L"¸", bimap_direction::left_to_right),
        lang_type_nc(L"JO",   L"¨", bimap_direction::all_to_all),
        lang_type_nc(L"Jo",   L"¸", bimap_direction::left_to_right),
        lang_type_nc(L"zh",   L"æ", bimap_direction::all_to_all),
        lang_type_nc(L"zH",   L"æ", bimap_direction::left_to_right),
        lang_type_nc(L"ZH",   L"Æ", bimap_direction::all_to_all),
        lang_type_nc(L"Zh",   L"Æ", bimap_direction::left_to_right),
        lang_type_nc(L"z",    L"ç", bimap_direction::all_to_all),
        lang_type_nc(L"Z",    L"Ç", bimap_direction::all_to_all),
        lang_type_nc(L"i",    L"è", bimap_direction::all_to_all),
        lang_type_nc(L"I",    L"È", bimap_direction::all_to_all),
        lang_type_nc(L"jj",   L"é", bimap_direction::all_to_all),
        lang_type_nc(L"jJ",   L"é", bimap_direction::left_to_right),
        lang_type_nc(L"JJ",   L"É", bimap_direction::all_to_all),
        lang_type_nc(L"Jj",   L"É", bimap_direction::left_to_right),
        lang_type_nc(L"k",    L"ê", bimap_direction::all_to_all),
        lang_type_nc(L"K",    L"Ê", bimap_direction::all_to_all),
        lang_type_nc(L"l",    L"ë", bimap_direction::all_to_all),
        lang_type_nc(L"L",    L"Ë", bimap_direction::all_to_all),
        lang_type_nc(L"m",    L"ì", bimap_direction::all_to_all),
        lang_type_nc(L"M",    L"Ì", bimap_direction::all_to_all),
        lang_type_nc(L"n",    L"í", bimap_direction::all_to_all),
        lang_type_nc(L"N",    L"Í", bimap_direction::all_to_all),
        lang_type_nc(L"o",    L"î", bimap_direction::all_to_all),
        lang_type_nc(L"O",    L"Î", bimap_direction::all_to_all),
        lang_type_nc(L"p",    L"ï", bimap_direction::all_to_all),
        lang_type_nc(L"P",    L"Ï", bimap_direction::all_to_all),
        lang_type_nc(L"r",    L"ð", bimap_direction::all_to_all),
        lang_type_nc(L"R",    L"Ð", bimap_direction::all_to_all),
        lang_type_nc(L"s",    L"ñ", bimap_direction::all_to_all),
        lang_type_nc(L"S",    L"Ñ", bimap_direction::all_to_all),
        lang_type_nc(L"t",    L"ò", bimap_direction::all_to_all),
        lang_type_nc(L"T",    L"Ò", bimap_direction::all_to_all),
        lang_type_nc(L"u",    L"ó", bimap_direction::all_to_all),
        lang_type_nc(L"U",    L"Ó", bimap_direction::all_to_all),
        lang_type_nc(L"f",    L"ô", bimap_direction::all_to_all),
        lang_type_nc(L"F",    L"Ô", bimap_direction::all_to_all),
        lang_type_nc(L"kh",   L"õ", bimap_direction::all_to_all),
        lang_type_nc(L"kH",   L"õ", bimap_direction::left_to_right),
        lang_type_nc(L"KH",   L"Õ", bimap_direction::all_to_all),
        lang_type_nc(L"Kh",   L"Õ", bimap_direction::left_to_right),
        lang_type_nc(L"c",    L"ö", bimap_direction::all_to_all),
        lang_type_nc(L"C",    L"Ö", bimap_direction::all_to_all),
        lang_type_nc(L"ch",   L"÷", bimap_direction::all_to_all),
        lang_type_nc(L"cH",   L"÷", bimap_direction::left_to_right),
        lang_type_nc(L"CH",   L"×", bimap_direction::all_to_all),
        lang_type_nc(L"Ch",   L"×", bimap_direction::left_to_right),
        lang_type_nc(L"sh",   L"ø", bimap_direction::all_to_all),
        lang_type_nc(L"sH",   L"ø", bimap_direction::left_to_right),
        lang_type_nc(L"SH",   L"Ø", bimap_direction::all_to_all),
        lang_type_nc(L"Sh",   L"Ø", bimap_direction::left_to_right),
        lang_type_nc(L"shh",  L"ù", bimap_direction::all_to_all),
        lang_type_nc(L"shH",  L"ù", bimap_direction::left_to_right),
        lang_type_nc(L"sHh",  L"ù", bimap_direction::left_to_right),
        lang_type_nc(L"sHH",  L"ù", bimap_direction::left_to_right),
        lang_type_nc(L"SHH",  L"Ù", bimap_direction::all_to_all),
        lang_type_nc(L"SHh",  L"Ù", bimap_direction::left_to_right),
        lang_type_nc(L"ShH",  L"Ù", bimap_direction::left_to_right),
        lang_type_nc(L"Shh",  L"Ù", bimap_direction::left_to_right),
        lang_type_nc(L"\"",   L"ú", bimap_direction::all_to_all),
        lang_type_nc(L"\"\"", L"Ú", bimap_direction::all_to_all),
        lang_type_nc(L"y",    L"û", bimap_direction::all_to_all),
        lang_type_nc(L"Y",    L"Û", bimap_direction::all_to_all),
        lang_type_nc(L"'",    L"ü", bimap_direction::all_to_all),
        lang_type_nc(L"''",   L"Ü", bimap_direction::all_to_all),
        lang_type_nc(L"eh",   L"ý", bimap_direction::all_to_all),
        lang_type_nc(L"eH",   L"ý", bimap_direction::left_to_right),
        lang_type_nc(L"EH",   L"Ý", bimap_direction::all_to_all),
        lang_type_nc(L"Eh",   L"Ý", bimap_direction::left_to_right),
        lang_type_nc(L"ju",   L"þ", bimap_direction::all_to_all),
        lang_type_nc(L"jU",   L"þ", bimap_direction::left_to_right),
        lang_type_nc(L"JU",   L"Þ", bimap_direction::all_to_all),
        lang_type_nc(L"Ju",   L"Þ", bimap_direction::left_to_right),
        lang_type_nc(L"ja",   L"ÿ", bimap_direction::all_to_all),
        lang_type_nc(L"jA",   L"ÿ", bimap_direction::left_to_right),
        lang_type_nc(L"JA",   L"ß", bimap_direction::all_to_all),
        lang_type_nc(L"Ja",   L"ß", bimap_direction::left_to_right),
    };

    p.m_translation.insert(translation, end(translation));
}