#include "stdafx.h"
#include "language.h"

// Standard
void Language::Reset1(LangProfile& rProfile)
{
	// Symbols
	static const LangType aSymbols[]=
	{
		LangType(L"a",L"à",Translate::trnsAll),
		LangType(L"A",L"À",Translate::trnsAll),
		LangType(L"b",L"á",Translate::trnsAll),
		LangType(L"B",L"Á",Translate::trnsAll),
		LangType(L"c",L"ö",Translate::trnsAll),
		LangType(L"C",L"Ö",Translate::trnsAll),
		LangType(L"ch",L"÷",Translate::trnsAll),
		LangType(L"cH",L"÷",Translate::trns1_2),
		LangType(L"CH",L"×",Translate::trnsAll),
		LangType(L"Ch",L"×",Translate::trns1_2),
		LangType(L"d",L"ä",Translate::trnsAll),
		LangType(L"D",L"Ä",Translate::trnsAll),
		LangType(L"e",L"å",Translate::trnsAll),
		LangType(L"E",L"Å",Translate::trnsAll),
		LangType(L"e'",L"¸",Translate::trnsAll),
		LangType(L"E'",L"¨",Translate::trnsAll),
		LangType(L"e`",L"ý",Translate::trnsAll),
		LangType(L"E`",L"Ý",Translate::trnsAll),
		LangType(L"e''",L"º",Translate::trnsAll),
		LangType(L"E''",L"ª",Translate::trnsAll),
		LangType(L"f",L"ô",Translate::trnsAll),
		LangType(L"F",L"Ô",Translate::trnsAll),
		LangType(L"g",L"ã",Translate::trnsAll),
		LangType(L"G",L"Ã",Translate::trnsAll),
		LangType(L"g'`",L"´",Translate::trnsAll),
		LangType(L"g`'",L"´",Translate::trns1_2),
		LangType(L"G'`",L"¥",Translate::trnsAll),
		LangType(L"G`'",L"¥",Translate::trns1_2),
		LangType(L"h",L"õ",Translate::trnsAll),
		LangType(L"H",L"Õ",Translate::trnsAll),
		LangType(L"i",L"è",Translate::trnsAll),
		LangType(L"I",L"È",Translate::trnsAll),
		LangType(L"i'",L"³",Translate::trnsAll),
		LangType(L"I'",L"²",Translate::trnsAll),
		LangType(L"i`",L"¿",Translate::trnsAll),
		LangType(L"I`",L"¯",Translate::trnsAll),
		LangType(L"j",L"æ",Translate::trnsAll),
		LangType(L"J",L"Æ",Translate::trnsAll),
		LangType(L"k",L"ê",Translate::trnsAll),
		LangType(L"K",L"Ê",Translate::trnsAll),
		LangType(L"l",L"ë",Translate::trnsAll),
		LangType(L"L",L"Ë",Translate::trnsAll),
		LangType(L"m",L"ì",Translate::trnsAll),
		LangType(L"M",L"Ì",Translate::trnsAll),
		LangType(L"n",L"í",Translate::trnsAll),
		LangType(L"N",L"Í",Translate::trnsAll),
		LangType(L"o",L"î",Translate::trnsAll),
		LangType(L"O",L"Î",Translate::trnsAll),
		LangType(L"p",L"ï",Translate::trnsAll),
		LangType(L"P",L"Ï",Translate::trnsAll),
		LangType(L"q",L"û",Translate::trns1_2),
		LangType(L"Q",L"Û",Translate::trns1_2),
		LangType(L"r",L"ð",Translate::trnsAll),
		LangType(L"R",L"Ð",Translate::trnsAll),
		LangType(L"s",L"ñ",Translate::trnsAll),
		LangType(L"S",L"Ñ",Translate::trnsAll),
		LangType(L"sh",L"ø",Translate::trnsAll),
		LangType(L"sH",L"ø",Translate::trns1_2),
		LangType(L"SH",L"Ø",Translate::trnsAll),
		LangType(L"Sh",L"Ø",Translate::trns1_2),
		LangType(L"sh''",L"ù",Translate::trns1_2),
		LangType(L"sH''",L"ù",Translate::trns1_2),
		LangType(L"Sh''",L"Ù",Translate::trns1_2),
		LangType(L"SH''",L"Ù",Translate::trns1_2),
		LangType(L"sch'",L"ù",Translate::trnsAll),
		LangType(L"sCh'",L"ù",Translate::trns1_2),
		LangType(L"scH'",L"ù",Translate::trns1_2),
		LangType(L"sCH'",L"ù",Translate::trns1_2),
		LangType(L"Sch'",L"Ù",Translate::trns1_2),
		LangType(L"SCh'",L"Ù",Translate::trns1_2),
		LangType(L"ScH'",L"Ù",Translate::trns1_2),
		LangType(L"SCH'",L"Ù",Translate::trnsAll),
		LangType(L"t",L"ò",Translate::trnsAll),
		LangType(L"T",L"Ò",Translate::trnsAll),
		LangType(L"tc'",L"ö",Translate::trns1_2),
		LangType(L"tC'",L"ö",Translate::trns1_2),
		LangType(L"Tc'",L"Ö",Translate::trns1_2),
		LangType(L"TC'",L"Ö",Translate::trns1_2),
		LangType(L"u",L"ó",Translate::trnsAll),
		LangType(L"U",L"Ó",Translate::trnsAll),
		LangType(L"u'",L"¢",Translate::trnsAll),
		LangType(L"U'",L"¡",Translate::trnsAll),
		LangType(L"v",L"â",Translate::trnsAll),
		LangType(L"V",L"Â",Translate::trnsAll),
		LangType(L"w",L"ø",Translate::trns1_2),
		LangType(L"W",L"Ø",Translate::trns1_2),
		LangType(L"w''",L"ù",Translate::trns1_2),
		LangType(L"W''",L"Ù",Translate::trns1_2),
		LangType(L"x",L"õ",Translate::trns1_2),
		LangType(L"X",L"Õ",Translate::trns1_2),
		LangType(L"y",L"é",Translate::trnsAll),
		LangType(L"Y",L"É",Translate::trnsAll),
		LangType(L"ya",L"ÿ",Translate::trnsAll),
		LangType(L"yA",L"ÿ",Translate::trns1_2),
		LangType(L"YA",L"ß",Translate::trnsAll),
		LangType(L"Ya",L"ß",Translate::trns1_2),
		LangType(L"yu",L"þ",Translate::trnsAll),
		LangType(L"yU",L"þ",Translate::trns1_2),
		LangType(L"YU",L"Þ",Translate::trnsAll),
		LangType(L"Yu",L"Þ",Translate::trns1_2),
		LangType(L"y'",L"û",Translate::trnsAll),
		LangType(L"Y'",L"Û",Translate::trnsAll),
		LangType(L"z",L"ç",Translate::trnsAll),
		LangType(L"Z",L"Ç",Translate::trnsAll),
		LangType(L"'",L"ü",Translate::trnsAll),
		LangType(L"''",L"Ü",Translate::trnsAll),
		LangType(L"`",L"ú",Translate::trnsAll),
		LangType(L"``",L"Ú",Translate::trnsAll),
	};
	rProfile.m_aSymbols.assign(aSymbols,
		aSymbols+sizeof(aSymbols)/sizeof(aSymbols[0]));

	// Name
	static const wchar_t strName[]=L"Standard";
	rProfile.m_strName=strName;

	// Ignore
	rProfile.ResetIgnore();
}