#include "stdafx.h"
#include "language.h"

// GOST
void Language::Reset3(LangProfile& rProfile)
{
	// Symbols
	static const LangType aSymbols[]=
	{
		LangType(L"a",L"à",Translate::trnsAll),
		LangType(L"A",L"À",Translate::trnsAll),
		LangType(L"b",L"á",Translate::trnsAll),
		LangType(L"B",L"Á",Translate::trnsAll),
		LangType(L"v",L"â",Translate::trnsAll),
		LangType(L"V",L"Â",Translate::trnsAll),
		LangType(L"g",L"ã",Translate::trnsAll),
		LangType(L"G",L"Ã",Translate::trnsAll),
		LangType(L"d",L"ä",Translate::trnsAll),
		LangType(L"D",L"Ä",Translate::trnsAll),
		LangType(L"e",L"å",Translate::trnsAll),
		LangType(L"E",L"Å",Translate::trnsAll),
		LangType(L"jo",L"¸",Translate::trnsAll),
		LangType(L"jO",L"¸",Translate::trns1_2),
		LangType(L"JO",L"¨",Translate::trnsAll),
		LangType(L"Jo",L"¸",Translate::trns1_2),
		LangType(L"zh",L"æ",Translate::trnsAll),
		LangType(L"zH",L"æ",Translate::trns1_2),
		LangType(L"ZH",L"Æ",Translate::trnsAll),
		LangType(L"Zh",L"Æ",Translate::trns1_2),
		LangType(L"z",L"ç",Translate::trnsAll),
		LangType(L"Z",L"Ç",Translate::trnsAll),
		LangType(L"i",L"è",Translate::trnsAll),
		LangType(L"I",L"È",Translate::trnsAll),
		LangType(L"jj",L"é",Translate::trnsAll),
		LangType(L"jJ",L"é",Translate::trns1_2),
		LangType(L"JJ",L"É",Translate::trnsAll),
		LangType(L"Jj",L"É",Translate::trns1_2),
		LangType(L"k",L"ê",Translate::trnsAll),
		LangType(L"K",L"Ê",Translate::trnsAll),
		LangType(L"l",L"ë",Translate::trnsAll),
		LangType(L"L",L"Ë",Translate::trnsAll),
		LangType(L"m",L"ì",Translate::trnsAll),
		LangType(L"M",L"Ì",Translate::trnsAll),
		LangType(L"n",L"í",Translate::trnsAll),
		LangType(L"N",L"Í",Translate::trnsAll),
		LangType(L"o",L"î",Translate::trnsAll),
		LangType(L"O",L"Î",Translate::trnsAll),
		LangType(L"p",L"ï",Translate::trnsAll),
		LangType(L"P",L"Ï",Translate::trnsAll),
		LangType(L"r",L"ð",Translate::trnsAll),
		LangType(L"R",L"Ð",Translate::trnsAll),
		LangType(L"s",L"ñ",Translate::trnsAll),
		LangType(L"S",L"Ñ",Translate::trnsAll),
		LangType(L"t",L"ò",Translate::trnsAll),
		LangType(L"T",L"Ò",Translate::trnsAll),
		LangType(L"u",L"ó",Translate::trnsAll),
		LangType(L"U",L"Ó",Translate::trnsAll),
		LangType(L"f",L"ô",Translate::trnsAll),
		LangType(L"F",L"Ô",Translate::trnsAll),
		LangType(L"kh",L"õ",Translate::trnsAll),
		LangType(L"kH",L"õ",Translate::trns1_2),
		LangType(L"KH",L"Õ",Translate::trnsAll),
		LangType(L"Kh",L"Õ",Translate::trns1_2),
		LangType(L"c",L"ö",Translate::trnsAll),
		LangType(L"C",L"Ö",Translate::trnsAll),
		LangType(L"ch",L"÷",Translate::trnsAll),
		LangType(L"cH",L"÷",Translate::trns1_2),
		LangType(L"CH",L"×",Translate::trnsAll),
		LangType(L"Ch",L"×",Translate::trns1_2),
		LangType(L"sh",L"ø",Translate::trnsAll),
		LangType(L"sH",L"ø",Translate::trns1_2),
		LangType(L"SH",L"Ø",Translate::trnsAll),
		LangType(L"Sh",L"Ø",Translate::trns1_2),
		LangType(L"shh",L"ù",Translate::trnsAll),
		LangType(L"shH",L"ù",Translate::trns1_2),
		LangType(L"sHh",L"ù",Translate::trns1_2),
		LangType(L"sHH",L"ù",Translate::trns1_2),
		LangType(L"SHH",L"Ù",Translate::trnsAll),
		LangType(L"SHh",L"Ù",Translate::trns1_2),
		LangType(L"ShH",L"Ù",Translate::trns1_2),
		LangType(L"Shh",L"Ù",Translate::trns1_2),
		LangType(L"\"",L"ú",Translate::trnsAll),
		LangType(L"\"\"",L"Ú",Translate::trnsAll),
		LangType(L"y",L"û",Translate::trnsAll),
		LangType(L"Y",L"Û",Translate::trnsAll),
		LangType(L"'",L"ü",Translate::trnsAll),
		LangType(L"''",L"Ü",Translate::trnsAll),
		LangType(L"eh",L"ý",Translate::trnsAll),
		LangType(L"eH",L"ý",Translate::trns1_2),
		LangType(L"EH",L"Ý",Translate::trnsAll),
		LangType(L"Eh",L"Ý",Translate::trns1_2),
		LangType(L"ju",L"þ",Translate::trnsAll),
		LangType(L"jU",L"þ",Translate::trns1_2),
		LangType(L"JU",L"Þ",Translate::trnsAll),
		LangType(L"Ju",L"Þ",Translate::trns1_2),
		LangType(L"ja",L"ÿ",Translate::trnsAll),
		LangType(L"jA",L"ÿ",Translate::trns1_2),
		LangType(L"JA",L"ß",Translate::trnsAll),
		LangType(L"Ja",L"ß",Translate::trns1_2),
	};
	rProfile.m_aSymbols.assign(aSymbols,
		aSymbols+sizeof(aSymbols)/sizeof(aSymbols[0]));

	// Name
	static const wchar_t strName[]=L"Symbols";
	rProfile.m_strName=strName;

	// Ignore
	rProfile.ResetIgnore();
}