//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Transliterator.rc
//
#define IDR_TRANSLITERATOR              100
#define IDD_PAGEGENERAL                 201
#define IDD_PAGEHOTKEYS                 202
#define IDD_PAGEPROFILE                 203
#define IDD_PAGEIGNORE                  204
#define IDD_ABOUT                       205
#define IDD_TRANSLATEFILES              206
#define IDD_OPTIONS                     207
#define IDD_TRANSLATION                 208
#define IDR_TRAYICON                    209
#define IDR_PROFILE                     210
#define IDR_EDIT                        211
#define IDC_TRNS                        1000
#define IDC_RUS                         1001
#define IDC_STRNSTEXT                   1002
#define IDC_SRUSTEXT                    1003
#define IDC_PROFILE                     1004
#define IDC_SPROFILE                    1005
#define IDC_EMAIL                       1006
#define IDC_SITE                        1007
#define IDC_SABOUT                      1008
#define IDC_SABOUTPROGRAM               1009
#define IDC_TRNSTORUS                   1010
#define IDC_RUSTOTRNS                   1011
#define IDC_PATH                        1012
#define IDC_BROWSE                      1013
#define IDC_FILES                       1014
#define IDC_FOLDERS                     1015
#define IDC_SUBFOLDERS                  1016
#define IDC_SELFOLDER                   1017
#define IDC_NAME                        1018
#define IDC_ENTRY                       1019
#define IDC_MP3TAGS                     1020
#define IDC_TRANSLATE                   1021
#define IDC_CLOSE                       1022
#define IDC_SDIRECTION                  1023
#define IDC_SFOLDER                     1024
#define IDC_SPATH                       1025
#define IDC_SFILE                       1026
#define IDC_PROFILENAME                 1027
#define IDC_SNAME                       1028
#define IDC_TRANSLATION                 1029
#define IDC_STRANSLIT                   1030
#define IDC_SRUSSIAN                    1031
#define IDC_ADD                         1032
#define IDC_REMOVE                      1033
#define IDC_SCOPYPROFILE                1034
#define IDC_ADD2                        1035
#define IDC_COPYFROM                    1036
#define IDC_SIGNORE                     1037
#define IDC_COPY                        1038
#define IDC_BEGINTRNS                   1039
#define IDC_ENDTRNS                     1040
#define IDC_BEGINRUS                    1041
#define IDC_ENDRUS                      1042
#define IDC_STRANSLIT2                  1043
#define IDC_SRUSSIAN2                   1044
#define IDC_SBEGIN                      1045
#define IDC_SEND                        1046
#define IDC_SBEGIN2                     1047
#define IDC_SEND2                       1048
#define IDC_RESET                       1049
#define IDC_RESETALL                    1050
#define IDC_SRESET                      1051
#define IDC_LISTOPTIONS                 1052
#define IDC_APPLY                       1053
#define IDC_SDLGPLACE                   1054
#define IDC_SIN							1055
#define IDC_STRANSLATESYMBOLS           1056
#define IDC_CLEAR                       1057
#define IDC_SFONTS                      1058
#define IDC_FONTTRNS                    1059
#define IDC_FONTRUS                     1060
#define IDC_FONTTRANSLATION             1061
#define IDC_SHOWTRAYICON                1062
#define IDC_SLOADONSTARTUP              1063
#define IDC_LOADNO                      1064
#define IDC_LOADSHOWN                   1065
#define IDC_LOADHIDDEN                  1066
#define IDC_SACTION                     1067
#define IDC_HOTKEYACTION                1068
#define IDC_SKEY                        1069
#define IDC_SHOTKEYS                    1070
#define IDC_SAUTOTRANSLATION            1071
#define IDC_ACTION                      1072
#define IDC_SVIEW                       1073
#define IDC_SHOWTASKBAR                 1074
#define IDC_FONTNAMETRNS                1075
#define IDC_FONTNAMERUS                 1076
#define IDC_FONTNAMETRANSLATION         1077
#define IDC_COPYIGNORE                  1078
#define IDC_SAVE                        1079
#define IDC_LOAD                        1080
#define IDC_SLOADSAVE                   1081
#define IDC_TOPMOST                     1082
#define IDC_LISTIGNORE                  1083
#define IDC_IGNORE                      1084
#define IDC_STEXT                       1085
#define ID_PROFILE                      32780
#define ID_EDIT_IGNORE_INSERT           32783
#define ID_EDIT_IGNORE_REMOVE           32784
#define ID_EDIT_COPY_TRNSTORUS          32785
#define ID_EDIT_COPY_RUSTOTRNS          32786
#define ID_VIEW_LANGUAGE_ENGLISH        32787
#define ID_VIEW_LANGUAGE_RUSSIAN        32788
#define ID_VIEW_LANGUAGE_TRANSLIT       32789
#define ID_VIEW_CONTROLS_WRAPTEXT       32790
#define ID_VIEW_CONTROLS_SCROLLTEXT     32791
#define ID_VIEW_CONTROLS_AUTOTRANSLITERATION 32792
#define ID_VIEW_CONTROLS_AUTOIGNORE     32793
#define ID_TOOLS_TRANSLATION            32794
#define ID_TOOLS_TRANSLATEFILES         32795
#define ID_TOOLS_OPTIONS                32796
#define ID_SHOW                         32797
#define ID_HIDE                         32798
#define IDC_STATICSEPARATOR             32799
#define ID_PROFILE1                     32801
#define ID_PROFILE2                     32802
#define ID_PROFILE3                     32803
#define ID_PROFILE4                     32804
#define ID_PROFILE5                     32805
#define ID_PROFILE6                     32806
#define ID_PROFILE7                     32807
#define ID_PROFILE8                     32808
#define ID_PROFILE9                     32809
#define ID_COUNTTRNS                    32810
#define ID_COUNTRUS                     32811
#define IDS_ERROR                       62000
#define IDS_HELP                        62001
#define IDS_TRNSTORUS                   62002
#define IDS_RUSTOTRNS                   62003
#define IDS_NOTRANSLATE                 62004
#define IDS_GENERAL                     62005
#define IDS_HOTKEYS                     62006
#define IDS_PROFILE                     62007
#define IDS_IGNORE                      62008
#define IDS_TRANSLIT                    62009
#define IDS_RUSSIAN                     62010
#define IDS_ALL                         62011
#define IDS_DONE                        62021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
