//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Translit.rc
//
#define IDR_TRANSLIT                    129
#define IDR_TRAY                        130
#define IDD_ABOUT                       131
#define IDD_TRANSLATION                 132
#define IDD_GENERALPAGE                 133
#define IDD_LAYOUTPAGE                  134
#define IDD_HOTKEYSPAGE                 135
#define IDD_AUTOTRANSLATIONPAGE         136
#define IDD_CHANGETRANSLATION           137
#define IDD_TRANSLATEFILES              138
#define IDC_ENG                         1001
#define IDC_RUS                         1002
#define IDC_SENGTEXT                    1003
#define IDC_SRUSTEXT                    1004
#define IDC_SSEPARATOR                  1005
#define IDC_EMAIL                       1006
#define IDC_SITE                        1007
#define IDC_TRANSLATION                 1008
#define IDC_ENGFONT                     1009
#define IDC_RUSFONT                     1010
#define IDC_CLOSEEXIT                   1011
#define IDC_CLOSETOTRAY                 1012
#define IDC_MINIMIZENORMAL              1013
#define IDC_MINIMIZETOTRAY              1014
#define IDC_LOADONSTARTUP               1015
#define IDC_HOTKEYSHOWTRANSLIT          1016
#define IDC_HOTKEYHIDETRANSLIT          1017
#define IDC_HOTKEYTRANSLATIONENGTORUS   1018
#define IDC_HOTKEYTRANSLATIONRUSTOENG   1019
#define IDC_SABOUT                      1020
#define IDC_SABOUTTRANSLIT              1021
#define IDC_STRANSLATION                1022
#define IDC_SENGTORUS                   1023
#define IDC_SRUSTOENG                   1024
#define IDC_STRANSLIT                   1025
#define IDC_SSHOW                       1026
#define IDC_SHIDE                       1027
#define IDC_SCLOSE                      1028
#define IDC_SFONTS                      1029
#define IDC_SMINIMIZE                   1030
#define IDC_STRAYICON                   1031
#define IDC_SSTARTUP                    1032
#define IDC_TRAYICONSHOWN               1033
#define IDC_TRAYICONHIDDEN              1034
#define IDC_SENG                        1035
#define IDC_SRUS                        1036
#define IDC_STRANSLATE                  1037
#define IDC_SNOTTRANSLATE               1038
#define IDC_SFROM1                      1039
#define IDC_SFROM2                      1040
#define IDC_STO1                        1041
#define IDC_STO2                        1042
#define IDC_FROMENG                     1043
#define IDC_TOENG                       1044
#define IDC_FROMRUS                     1045
#define IDC_TORUS                       1046
#define IDC_ADD                         1047
#define IDC_REMOVE                      1048
#define IDC_CLEAR                       1049
#define IDC_RESET                       1050
#define IDC_COPYNOTTRANSLATE            1051
#define IDC_ENGTORUS                    1052
#define IDC_RUSTOENG                    1053
#define IDC_PATH                        1054
#define IDC_BROWSE                      1055
#define IDC_FILES                       1056
#define IDC_DIRECTORIES                 1057
#define IDC_SUBDIRECTORIES              1058
#define IDC_THISDIRECTORY               1059
#define IDC_NAME                        1060
#define IDC_ENTRY                       1061
#define IDC_MP3TAGS                     1062
#define IDC_TRANSLATE                   1063
#define IDC_CLOSE                       1064
#define IDC_SDIRECTION                  1065
#define IDC_SDIRECTORY                  1066
#define IDC_SPATH                       1067
#define IDC_SFILE                       1068
#define IDC_HOTKEYTRANSLATIONAUTO       1069
#define IDC_SHOTKEY                     1071
#define IDC_SDEFAULT                    1072
#define IDC_SDEFAULTTRANSLATION         1072
#define IDC_SAUTOTRANSLATION            1075
#define ID_EDIT_ENG_UNDO                32775
#define ID_EDIT_ENG_REDO                32776
#define ID_EDIT_ENG_CUT                 32777
#define ID_EDIT_ENG_COPY                32778
#define ID_EDIT_ENG_PASTE               32779
#define ID_EDIT_ENG_SELECTALL           32780
#define ID_EDIT_ENG_DELETE              32781
#define ID_EDIT_ENG_DELETEALL           32782
#define ID_EDIT_RUS_UNDO                32783
#define ID_EDIT_RUS_REDO                32784
#define ID_EDIT_RUS_CUT                 32785
#define ID_EDIT_RUS_COPY                32786
#define ID_EDIT_RUS_PASTE               32787
#define ID_EDIT_RUS_SELECTALL           32788
#define ID_EDIT_RUS_DELETE              32789
#define ID_EDIT_RUS_DELETEALL           32790
#define ID_TOOLS_OPTIONS                32791
#define ID_TOOLS_LANGUAGE_ENGLISH       32792
#define ID_TOOLS_LANGUAGE_RUSSIAN       32793
#define ID_TOOLS_TRANSLATION            32794
#define ID_TOOLS_CHANGETRANSLATION      32795
#define ID_TOOLS_TRANSLATEFILES         32796
#define ID_SHOW                         32797
#define ID_HIDE                         32798
#define ID_EDIT_NOTRANSLATE_SET         32810
#define ID_EDIT_NOTRANSLATE_CLEAR       32811
#define ID_EDIT_WRAPTEXT                32815
#define IDS_OPTIONS                     63005
#define IDS_ENGTORUS                    63006
#define IDS_RUSTOENG                    63007
#define IDS_AREYOUSURE                  63008
#define IDS_RESET                       63009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           139
#endif
#endif
